name: Security

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "0 4 * * 1"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  secrets:
    permissions:
      contents: read
    uses: nabhold/shared/.github/workflows/security-secrets-scan.yml@c0b1dfcb5049f4e994e926a6f1ea9ff2b4a02b6c # v1.3.0

  codeql:
    permissions:
      actions: read
      contents: read
      security-events: write
      packages: read
    uses: nabhold/shared/.github/workflows/security-codeql.yml@c0b1dfcb5049f4e994e926a6f1ea9ff2b4a02b6c # v1.3.0
    with:
      languages: '["python", "java"]'
